#!/bin/bash -f
/bin/rm driver.o
/bin/rm enks.o
/bin/rm kwm_date_utilities.mod
/bin/rm kwm_date_utilities.o
/bin/rm module_model_constants.mod
/bin/rm module_model_constants.o
/bin/rm module_sf_noahlsm.mod
/bin/rm module_sf_noahlsm.o
/bin/rm module_sf_noahmplsm.mod
/bin/rm module_sf_noahmplsm.o
/bin/rm module_sf_noahutl.mod
/bin/rm module_sf_noahutl.o
/bin/rm noahmp_globals.mod
/bin/rm noahmp_rad_parameters.mod
/bin/rm noahmp_routines.mod
/bin/rm noahmp_veg_parameters.mod
/bin/rm type_decs.mod
/bin/rm type_decs.o
/bin/rm rmse_obj_fun.o
/bin/rm objfun.o
